#!/usr/bin/bash

# status percent number (less equal than)
critical_percent=10
low_percent=20
medium_percent=40

# colors
red="#FF0000"
orange="#FFA500"
yellow="#FFFF00"
green="#00FF00"

# icons for the label (FontAwesome)
bat_empty=""
bat_low=""
bat_medium=""
bat_avg=""
bat_full=""
charging=""
loading=""

# main command (acpi)
output=$(acpi -b)

# get current battery percentual charge
percent=$(echo "$output" | cut -d " " -f4 | tr -d ,%)

#get current estimated time for charging|discharging
estimated_time() {
	_time="$(echo $output | cut -d " " -f5 | cut -c1-5 | tr -d a-zA-Z )"
	if [[ -n $_time ]]; then
		_hour=$(echo $_time | cut -c1-2)
		_minutes=$(echo $_time | cut -c4-5)
		if [[ $_hour -eq 0 ]];then
			_hour=""
			_minutes="${_minutes}m"
		else
			_hour="${_hour}h"
			_minutes="${_minutes}"
		fi
		_time="($_hour$_minutes)"
	fi
	echo $_time;
}

if [[ -n $(echo $output | grep Charging) ]]; then
	label=$charging
	estimated=`estimated_time`
	if [[ $percent -eq 100 ]]; then
		color=$green
	fi
else
	if [[ -n $(echo $output | grep Unknown) ]]; then
		# disabled due to acpi reporting Unknown behavior in some actually known momments
		label=$charging
		color=$green
	elif [[ -n $(echo $output | grep Full) ]]; then
		label=$charging
		color=$green
	elif [[ $percent -lt $critical_percent ]]; then
		color=$red
		label=$bat_empty
	elif [[ $percent -lt $low_percent ]]; then
		color=$orange
		label=$bat_medium
	elif [[ $percent -lt $medium_percent ]]; then
		color=$yellow
		label=$bat_avg
	else
		label=$bat_full
	fi

	if [[ -n $(echo $output | grep Discharging) ]]; then
		estimated=`estimated_time`
	fi
fi


echo "$label $percent%$estimated"	# full text
echo "$label $percent%$estimated"	# short text
echo "$color"				# display color
