#!/usr/bin/bash

# colors
red="#FF0000"
orange="#FFA500"
yellow="#FFFF00"
green="#00FF00"

# icons for the label (FontAwesome)
bat_empty=""
bat_low=""
bat_medium=""
bat_avg=""
bat_full=""
charging=""
loading=""

# main command (acpi)
output=$(acpi -b)

# get current battery percentual charge
percent=$(echo "$output" | cut -d " " -f4 | tr -d ,%)

if [[ -n $(echo $output | grep Charging) ]]; then
	label=$charging
	if [[ $percent -eq 100 ]]; then
		color=$green
	fi
else
	if [[ -n $(echo $output | grep Unknown) ]]; then
		# disabled due to acpi reporting Unknown behavior in some actually known momments
		# label=$loading
		label=$charging
	elif [[ $percent -lt 10 ]]; then
		color=$red
		label=$bat_empty
	elif [[ $percent -lt 20 ]]; then
		color=$red
		label=$bat_low
	elif [[ $percent -lt 40 ]]; then
		color=$orange
		label=$bat_medium
	elif [[ $percent -lt 70 ]]; then
		color=$yellow
		label=$bat_avg
	else
		label=$bat_full
	fi

	if [[ -n $(echo $output | grep Discharging) ]]; then
		estimated="$(echo $output | cut -d " " -f5 | cut -c1-5 | tr -d a-zA-Z )"
		if [[ -n $estimated ]]; then
			hour=$(echo $estimated | cut -c1-2)
			minutes=$(echo $estimated | cut -c4-5)
			if [[ $hour -eq 0 ]];then
				hour=""
				minutes="${minutes}m"
			else
				hour="${hour}h"
				minutes="${minutes}"
			fi
			estimated="($hour$minutes)"
		fi
	fi
fi

echo "$label $percent%$estimated"	# full text
echo "$label $percent%$estimated"	# short text
echo "$color"				# display color
