#!/bin/sh

# TODO it runs fine when in terminal, but in i3block it shows wrong results
#OUTPUT=$(cat /proc/cpuinfo | awk '/^cpu MHz/ { print (int($4 / 100) / 10) " GHz" }' | head -n1)
OUTPUT=$(lscpu | awk '/^CPU MHz/ { print (int($3 / 100) / 10) " GHz" }')

echo "$OUTPUT"
