#!/usr/bin/env bash

PLAYER=$BLOCK_INSTANCE
LABEL=""

if [ $(playerctl status) != "No players found" ]; then
	LONG_OUTPUT=$(playerctl --player=$PLAYER metadata --format "{{ artist }} - {{ title }}")
	SHORT_OUTPUT=$(playerctl --player=$PLAYER status)
	if [ "$PLAYER" == "spotify" ]; then
		LABEL=
		COLOR="#84bd00"
	else
		LABEL=
		COLOR=""
	fi

	case $BLOCK_BUTTON in
		1) notify-send "$(echo -e 'Track:\t' $(playerctl metadata title) '\nArtist:\t' $(playerctl metadata artist) '\nAlbum:\t' $(playerctl metadata album))" ;;
	esac

	echo "$LABEL $LONG_OUTPUT" # long text
	echo "$LABEL $SHORT_OUTPUT" # short text
	echo $COLOR
	echo ""
fi

