#!/usr/bin/env bash

PLAYER=$BLOCK_INSTANCE
LONG_OUTPUT=$(playerctl --player=$PLAYER metadata --format "{{ artist }} - {{ title }}")
SHORT_OUTPUT=$(playerctl --player=$PLAYER status)

if [[ $PLAYER -eq "spotify" ]]; then
	LABEL=
	COLOR="#84bd00"
else
	LABEL=
	COLOR=""
fi

echo "$LABEL $LONG_OUTPUT" # long text
echo "$LABEL $SHORT_OUTPUT" # short text
echo $COLOR
echo ""
