#!/bin/sh

MEM=`free -m | awk '/^Mem:/ { print "scale=1;" $7 " / 1000" }' | bc | sed 's/^\./0./'`

case $BLOCK_BUTTON in
	1) exec notify-send "Memory usage" "$(ps -o %mem,fname,pid --sort -%mem | head -n 11 )";;
esac


echo "${MEM}G"
test $MEM -le 200 && exit 33 || exit 0
