#!/bin/sh

interface="${BLOCK_INSTANCE:-wlan0}"

test ! -d "/sys/class/net/${interface}/wireless" || test "$(cat "/sys/class/net/$interface/operstate")" = 'down' && exit

quality=$(grep "$interface" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

label=
long_text=""
short_text=""
color=""

if [ "$quality" -ge 80 ]; then
    color="#00FF00"
elif [ "$quality" -ge 60 ]; then
    color="#FFF600"
elif [ "$quality" -ge 40 ]; then
    color="#FFAE00"
else
    color="#FF0000"
fi

case $BLOCK_BUTTON in
    1) long_text="${quality}%" ;;
esac

echo "$label $long_text"
echo "$label $short_text"
echo "$color"
