#!/bin/sh

OPTION=$(cat $1 | dmenu -i)

case $OPTION in
	"Firefox")			exec firefox ;;
	"Telegram")			exec telegram-desktop ;;
	"WhatsApp")			exec whatsie ;;
	"Spotify")			exec spotify ;;
	"Steam")			exec steam ;;
	"PCManFM File Manager")		exec pcmanfm -n $(xdg-user-dir DESKTOP) ;;
	"Camera")			exec xawtv -c /dev/video0 ;;
	"Appearance")			exec lxappearance ;;
	"Gimp Image Editor")		exec gimp ;;
	"Thunderbird Mail")		exec thunderbird ;;
	"Network Manager")		exec nm-applet ;;
	"Pavucontrol Volume Control")	exec pavucontrol ;;
	"Lutris")			exec lutris ;;
	"GitKraken")			exec gitkraken ;;
	"Visual Studio Code")		exec code ;;
esac
